=== guledibrahim/XML-blog/blog.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="blog">
		<xsd:complexType>
			<xsd:sequence> 	
			
			
			<xsd:element name="blogitems" minOccurs="1" maxOccurs="unbounded">
			       	<xsd:complexType>
			       			<xsd:sequence> 
	
			       			<xsd:element name="headline" minOccurs="1" maxOccurs="1">
				    				<xsd:simpleType>
						   					 <xsd:restriction base="xsd:string">	
                              					<xsd:maxLength value="100"/>
						    				</xsd:restriction>
			    					</xsd:simpleType>
			    			</xsd:element<name />
			       						       			
			       				
			<xsd:element name="date" minOccurs="1" maxOccurs="1">
			       <xsd:simpleType>
                      <xsd:restriction base="xsd:string">
                        <xsd:pattern value="\d{2}-\d{2}-\d{4}"/>
                      </xsd:restriction>
                </xsd:simpleType>
                </xsd:element>
			       			      					       			
			       			                           
			<xsd:element name="time" minOccurs="1" maxOccurs="1">
			     <xsd:simpleType>
                     <xsd:restriction base="xsd:string">
                       <xsd:pattern value="\d{2}:\d{2}"/>
                     </xsd:restriction>
                 </xsd:simpleType>
                 </xsd:element>
                 
                 
			<xsd:element name="author" minOccurs="1" maxOccurs="1" fixed="By Guled Ibrahim"/>	

			<xsd:element name="image" minOccurs="0" maxOccurs="1"/>	
		  		
		    		      
			<xsd:element name="post" minOccurs="1" maxOccurs="1">
			    <xsd:simpleType>
						    <xsd:restriction base="xsd:string">	
                              <xsd:maxLength value="1000"/>
						    </xsd:restriction>
			    </xsd:simpleType>
			   </xsd:element>
			   			   					 			 

			 
			 <xsd:element name="source"  minOccurs="0" maxOccurs="1"/>
			
						 <xsd:element name="tags" minOccurs="1" maxOccurs="1">
					<xsd:simpleType>
						  <xsd:restriction base="xsd:string">
						  <xsd:maxLength value="50"/>
						  </xsd:restriction>
					</xsd:simpleType>
			 </xsd:element>
			


			       			</xsd:sequence> 
					</xsd:complexType>
			</xsd:element>
										 
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== guledibrahim/XML-blog/blog.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="blog.xslt"?> 
<!DOCTYPE xml>
<blog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="blog.xsd">
	
<blogitems>	
<headline>Arsenal Win Against Man City</headline>
<date>05-01-2015</date>
<time>19:30</time>
<author>By Guled Ibrahim</author> 
<image>images/santi.jpg</image>
<post>Arsenal have won their first away game against Manchester City since 2012, who have slipped against their title rival chelsea with a first half penalty put away by Santi Cazorla. Arsene Wenger tactical master plan was executed perfectly by siting back and being compact and hitting quick counter attacks on the break. A quick second half goal scored by Giroud to extend Arsenal leads. The match was very entertaining (of course being Arsenal fan) and seeing my team win away for the first in a long time. Manchester City have a tough away game against their title rival Chelsea which will be an exciting match. 
</post>
<source> http://www.bbc.co.uk/sport/0/football/30766356 </source>
<tags>Tags: Football Arsenal City Chelsea title-decider</tags>
</blogitems>

<blogitems>
<headline>Lewis Hamilton Wins Second F1 Championship</headline>
<date>23-11-2014</date>
<time>14:48</time>
<author>By Guled Ibrahim</author>
<image>images/lewis.jpg</image>
<post>Lewis Hamilton has won his second F1 championship in Abu Dhabi, the race was an heated race and not only because of the desert with Hamilton in the Mercedes watched by prince Harry who congratulated him by saying "you're ledgend, for not making the british public sweat". He became only the fourth man from these isles to win two world titles.He joined the distinguished company of Jim Clark, Graham Hill and our only triple champion Sir Jackie Stewart.</post>
<source>http://www.mirror.co.uk/sport/formula-1/lewis-hamilton-seals-second-f1-4679574</source>
<tags>Lewis Champion F1 Royal Family </tags>
</blogitems>


<blogitems>
<headline>Queen Elizabeth II visits the Tower of London for Poppy Memorial</headline>
<date>16-10-14</date>
<time>13:35</time>
<author>By Guled Ibrahim</author>
<image>images/queen.jpg</image>
<post>Her royal Higness Queen Elizabeth II visited the Tower of London to see the grand dispaly of poppies to honour the soldiers who fought. Amid the sea of ceramic blood red poppies, Her Majesty and the Duke of Edinburgh laid their own wreath to commemorate the dead. The creator, ceramic artist Paul Cummins, will fill the evolving installation with 888,246 poppies, honouring each British and Colonial soldier that died during the war. The last poppy will be planted on 11 November, symbolically marking the end of the First World War.
</post>
<source>http://www.itv.com/news/2014-10-16/queen-lays-wreath-at-tower-of-london-poppy-memorial/</source>
<tags>Queen Tower of London Word War One Veterans Poppies</tags>
</blogitems>



<blogitems>
<headline>Holy grail of huge waves</headline>
<date>11-12-2014</date>
<time>17:35</time>
<author>By Guled Ibrahim</author>
<image>images/surfer.jpg</image>
<post>The area of Portuguese coast is known for the enormous swells, with underwater canyon running right up to the shoreline cliffs, amplifying the waves that are created. The swells along the Praia do Norte are now known as creating some of the biggest surf in the world. Above, big-wave surfer Garrett McNamara drops in on a large wave at Praia do Norte in Nazare.</post>
<source>http://www.telegraph.co.uk/sport/picturegalleries/9837058/Hawaiian-surfer-Garrett-McNamara-rides-monster-waves-off-Nazare-Portugal.html?frame=2466037</source>
<tags>Surfer Largest Tidel Wave </tags>
</blogitems>





<blogitems>
<headline>Saudi Arabia's King Abdullah bin Abdulaziz dies</headline>
<date>23-01-2015</date>
<time>11:55</time>
<author>By Guled Ibrahim</author>
<image>images/king.jpg</image>
<post>Saudi King Abdullah bin Abdulaziz has died, royal officials have announced, weeks after he was admitted to hospital.
Abdullah, who had ruled since 2005 and was said to be aged about 90, had been suffering from a lung infection. His 79-year-old half-brother, Salman, has been confirmed as the new king. Within hours of his accession to the throne of the oil-rich kingdom, King Salman vowed to maintain the same policies as his predecessors. "We will continue adhering to the correct policies which Saudi Arabia has followed since its establishment," he said in a speech broadcast on state television. Abdullah had suffered frequent bouts of ill health in recent years, and King Salman had recently taken on the ailing monarch's responsibilities. Prior to announcing Abdullah's death, Saudi television cut to Koranic verses, which often signifies the passing of a senior royal.</post>
<source>http://www.bbc.co.uk/news/world-middle-east-30945324</source>
<tags>Saudi King Dies Oil Prices Brother</tags>
</blogitems>
</blog>
